language: node_js

node_js:
    - "node"
    - "10"
    - "8"
    - "6"

sudo: false

env:
    global:
        JWT_SECRET="jsksfnfisdjdsjsdjdskdfvmfdfsåpsdä2348ej383j"

git:
    submodules: false

before_script:
    - npm install

script:
    - npm test

after_success:
    - npm run report-coveralls
    - npm run report-codecov
